# Database and server configuration
[DEFAULT]
useSecureMode=1
eastURL=postgresql://stemp:BvRkdxN8dkthc5zuyPQ9HA@jaunty-coder-10457.jxf.gcp-us-east1.cockroachlabs.cloud:26257/defaultdb
westURL=postgresql://fidawi:Y5mcB5NSTFogAy06VW3oYg@uswest-10429.jxf.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb
centralURL=postgresql://fidawi:WrGtipsmQIbfSZA_H4yXXA@uscentral-10432.jxf.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb
GOOGLE_CLOUD_STORAGE_BUCKET="gs://cse512_cdb_1"
API_KEY_EC=CCDB1_lvWREcRl7F7gyWRg0UIlH4_7wJiJIeZVhaTLWUOe3rJeoE1T2SUFRU4aMljkxYE
API_KEY_W=CCDB1_mPCwUB4oDicisrdEieEFLl_E8FYr3J5d5Pcryc8qdvlqUVJQ8INQ9FWuQVpG8FI
remoteUSEastBackupURL=postgresql://stemp:BvRkdxN8dkthc5zuyPQ9HA@jaunty-coder-10457.jxf.gcp-us-east1.cockroachlabs.cloud:26257/defaultdb
remoteUSWestBackupURL=postgresql://stemp:BvRkdxN8dkthc5zuyPQ9HA@jaunty-coder-10457.jxf.gcp-us-east1.cockroachlabs.cloud:26257/defaultdb
remoteCentralBackupURL=postgresql://stemp:BvRkdxN8dkthc5zuyPQ9HA@jaunty-coder-10457.jxf.gcp-us-east1.cockroachlabs.cloud:26257/defaultdb