# Database and server configuration
# Fill in the values as needed. Leave empty for environment-based overrides.
[DEFAULT]
useSecureMode=1
eastURL=""
westURL=postgresql://fidawi:Y5mcB5NSTFogAy06VW3oYg@uswest-10429.jxf.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb
centralURL=postgresql://fidawi:WrGtipsmQIbfSZA_H4yXXA@uscentral-10432.jxf.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb
GOOGLE_CLOUD_STORAGE_BUCKET="gs://cse512_cdb_1"
API_KEY="CCDB1_lvWREcRl7F7gyWRg0UIlH4_7wJiJIeZVhaTLWUOe3rJeoE1T2SUFRU4aMljkxYE"
remoteUSEastBackupURL=postgresql://fidawi:WrGtipsmQIbfSZA_H4yXXA@uscentral-10432.jxf.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb
remoteUSWestBackupURL=postgresql://fidawi:WrGtipsmQIbfSZA_H4yXXA@uscentral-10432.jxf.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb
remoteCentralBackupURL=postgresql://fidawi:WrGtipsmQIbfSZA_H4yXXA@uscentral-10432.jxf.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb