# Database and server configuration
# Fill in the values as needed. Leave empty for environment-based overrides.
localDatabase1URL="postgresql://root@localhost:26261/defaultdb?sslmode=disable"
localDatabase2URL="postgresql://root@localhost:26262/defaultdb?sslmode=disable"
replicationServerURL="http://localhost:5003" #us-central
