# Database and server configuration
# Fill in the values as needed. Leave empty for environment-based overrides.
# WCE
localDatabaseURL="postgresql://root@localhost:26259/defaultdb?sslmode=disable"
localDatabase2URL="postgresql://root@localhost:26260/defaultdb?sslmode=disable"
replicationServer1URL="http://localhost:5001" #us-central
replicationServer2URL="http://localhost:5002" #us-east
ownUrl="http://localhost:5000" #us-west
