# Database and server configuration
# Fill in the values as needed. Leave empty for environment-based overrides.
# WCE
localDatabaseWURL="postgresql://root@localhost:26257/west?sslmode=disable"
localDatabaseCURL="postgresql://root@localhost:26257/central?sslmode=disable"
#replicationServer1URL="http://localhost:5000" #us-
ownURL="http://localhost:5002" #us-east
eastNodeURL="http://localhost:5000" #us-west
centralNodeURL="http://localhost:5001" #us-central