# Database and server configuration
# Fill in the values as needed. Leave empty for environment-based overrides.
localDatabase1URL="postgresql://root@localhost:26257/defaultdb?sslmode=disable"
localDatabase2URL="postgresql://root@localhost:26258/defaultdb?sslmode=disable"
replicationServerURL="http://localhost:5001" #us-east

