# Database and server configuration
# Fill in the values as needed. Leave empty for environment-based overrides.
localDatabaseURL="postgresql://root@localhost:26259/defaultdb?sslmode=disable"
localDatabase2URL="postgresql://root@localhost:26260/defaultdb?sslmode=disable"
replicationServerURL="http://localhost:5002" #us-central
